import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[cursor]
vi_mode_style = "Block"

[cursor.style]
shape = "Beam"

[env]
TERM = "xterm-256color"

[font.normal]
family = "monospace"
style = "Regular"

[font.offset]
x = 0
y = -1

[window]
opacity = 0.9

[window.padding]
x = 3
y = 0
